[package]
name = "rustrest_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.60", features = ["derive"]}
reqwest = { version = "0.13.2", features = ["json", "blocking"]}
serde_json = "1.0.149"
colored = "3.1.1"